[workspace]
members = [
    "lumen-core", 
]

[workspace.package]
version = "0.1.0"
edition = "2024"
repository = "https://github.com/MoleSir/lumen.git"
description = "A tiny ML framework"
keywords = ["machine-learning", "auto-grad"]
license = "MIT"

[workspace.dependencies]
lumen-core = { path = "./lumen-core", package = "lumen-core", version = "0.2.0" }

approx = "0.5.1"
derive_builder = "0.20.2"
num-traits = "0.2.19"
rand = "0.9.2"
rand_distr = "0.5.1"
tempfile = "3.21.0"
thiserror = "2.0.16"
paste = "1.0.15"
libm = "0.2.15"