[package]
name = "xor_gate"
version = "0.1.0"
edition = "2024"

[dependencies]
lumen-core = { path = "../../lumen-core" }
lumen-nn = { path = "../../lumen-nn" }
lumen-macros = { path = "../../lumen-macros" }