[package]
name = "iris"
version = "0.1.0"
edition = "2024"

[dependencies]
lumen-core = { path = "../../lumen-core" }
lumen-nn = { path = "../../lumen-nn" }
lumen-dataset = { path = "../../lumen-dataset" }